/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            colors: {
                primary: '#80b6d5',
                secondary: '#182934',
                'primary-txt': '#182934',
                'secondary-txt': '#6b8ba0',
                'primary-bg': '#dfebf6',
                'secondary-bg': '#f2f8fc',
                'components-bg': '#cee1f3',
                link: '#80b6d5',
                'link-hover': '#5c91b4',
                'primary-btn': '#80b6d5',
                'primary-btn-txt': '#ffffff',
                'primary-btn-hover': '#80b6d5',
                'secondary-btn': '#ffffff',
                'secondary-btn-txt': '#80b6d5',
                border: '#a0b3c1',
                'input-border': '#a0b3c1',
                'input-border-focus': '#80b6d5',
                info: '#2196f3',
                error: '#f44336',
                warning: '#ffc107',
                success: '#4caf50',
            },
            fontSize: {
                xsmall: '0.57rem' /* 14pt */,
                small: '0.73rem' /* 16pt */,
                normal: '1.07rem' /* 20pt */,
                large: '1.32rem' /* 23pt */,
                xlarge: '1.48rem' /*25pt */,
                '2xlarge': '1.85rem' /* 33pt */,
                '3xlarge': '2.48rem' /* 37pt */,
                '4xlarge': '3.03rem' /* 40pt */,
            },
        },
    },
    plugins: [],
};
